routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QaController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ParamController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\ProfilbuController;
use App\Http\Controllers\SetParamController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MyProfileController;
use App\Http\Controllers\SetKlasterController;
use App\Http\Controllers\SetPenggunaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [LoginController::class, 'index'])->middleware('guest')->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.post');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout.post');

//all
Route::get('/', [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');
Route::resource('/myprofile', MyProfileController::class)->middleware('auth');

//admin
Route::resource('/qa', QaController::class)->middleware('admin');
Route::resource('/setpengguna', SetPenggunaController::class)->middleware('admin');
Route::resource('/setparam', SetParamController::class)->middleware('admin');
Route::get('/setting/sima_klpbu', [SettingController::class, 'sima_klpbu'])->middleware('admin')->name('set_simaklpbu');

//mitra
Route::resource('/profilebu', ProfilbuController::class)->middleware('mitra');
Route::resource('/parameter', ParamController::class)->middleware('mitra');

app/Http/Controllers/SetPenggunaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Myprofile;
use App\Models\User;
use App\Models\Sima_klpbu;
use App\Models\Bu;
use App\Models\Klaster;
use Illuminate\Http\Request;

class SetPenggunaController extends Controller
{
    public function index()
    {
        $klaster = Klaster::all();
        $mitra = Myprofile::where('role', 'mitra')->count();
        $pengguna = Myprofile::get();
        $data = [
            'klaster' => $klaster,
            'pengguna' => $pengguna,
            'mitra' => $mitra
        ];
        return view('set_pengguna.index', $data);
    }


    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $user = new User();
        $user->username = $request->input('username');
        $user->password = bcrypt($request->input('password'));
        $user->save();

        $myprofile = new Myprofile();
        $myprofile->user_id = $user->id;
        $myprofile->name = $request->input('name');
        $myprofile->email = $request->input('email');
        $myprofile->phone = $request->input('phone');
        $myprofile->save();

        $bu = new Bu();
        $bu->myprofile_id = $user->id;
        $bu->kode_klpbu_id = $request->input('kode_klpbu_id');
        $bu->klaster_id = $request->input('klaster_id');
        $bu->save();

        // Additional logic if needed
        return redirect()->route('setpengguna.index')->with('success', 'Data stored successfully.');
    }

    public function show(Myprofile $myprofile)
    {
        //
    }

    public function edit($myprofile)
    {
    }

    public function update(Request $request, Myprofile $myprofile)
    {
        //
    }

    public function destroy($request)
    {
        Myprofile::destroy($request);
        User::destroy($request);
        return redirect(route('setpengguna.index'))->with('deleted', 'User has been deleted!');
    }
}

resources/views/set_pengguna/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <ul class="nav nav-pills flex-column flex-md-row mb-3">
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('setpengguna.index') }}"><i class="bx bx-user me-1"></i> Data Pengguna</a>
            </li>
            <li class="nav-item ms-2">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#tambah-pengguna">
                    <span class="tf-icons bx bx-plus"></span>&nbsp; Tambah Data
                </button>
            </li>
        </ul>

        <!-- Statistic users -->
        {{-- @include('set_pengguna.statistic') --}}
        <!-- Users List Table -->
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    @if (session()->has('success'))
                        <div class="alert alert-primary my-3 mx-3 alert-dismissible" role="alert">
                            {{ session('success') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    @if (session()->has('deleted'))
                        <div class="alert alert-danger my-3 mx-3 alert-dismissible" role="alert">
                            {{ session('deleted') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    <div class="card-body">
                        <div class="table-responsive text-nowrap">
                            <table class="table table-hover" id="set_pengguna">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Username</th>
                                        <th>Name</th>
                                        <th>Kode BU</th>
                                        <th>Nama BU</th>
                                        <th>Role</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody class="table-border-bottom-0">
                                    @foreach ($pengguna as $pengguna)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $pengguna->user->username }}</td>
                                            <td>{{ $pengguna->name }}</td>
                                            <td>
                                                @if ($pengguna->bu)
                                                    {{ $pengguna->bu->kode_klpbu_id }}
                                                @endif
                                            </td>
                                            <td>
                                                @if ($pengguna->bu)
                                                    {{ $pengguna->bu->sima_klpbu->nama_klpbu }}
                                                @endif
                                            </td>
                                            <td>{{ $pengguna->role }}</td>
                                            <td>{{ $pengguna->email }}</td>
                                            <td> <a target="blank" href="https://wa.me/62{{ $pengguna->phone }}">{{ '+62' . $pengguna->phone }}</a> </td>
                                            <td>
                                                <div class="dropdown">
                                                    <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                                                        <i class="bx bx-dots-vertical-rounded"></i>
                                                    </button>
                                                    <div class="dropdown-menu">
                                                        <form action="{{ route('setpengguna.destroy', $pengguna->id) }}" method="post">
                                                            @method('delete')
                                                            @csrf
                                                            <button type="submit" class="dropdown-item" onclick="return confirm('Are you sure?')"><i class="bx bx-trash me-1"></i> Delete</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                        <div class="card-footer border-top">
                            {{--  --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- / Content -->

    <!-- Modal tambah pengguna -->
    @include('set_pengguna.modal_tambah_pengguna')
    <!--/ Modal tambah pengguna -->

    @push('inlinejs')
        <script>
            $(document).ready(function() {
                $('#set_pengguna').DataTable();
                $('#edit-pengguna').on('click', '.edit-pengguna', function() {
                    var id_pengguna = $(this).attr('data-id');

                    if (id_pengguna) {

                        // AJAX request
                        var url = "{{ route('setpengguna.edit', [':setpengguna']) }}";
                        url = url.replace(':setpengguna', id_pengguna);

                        // Empty modal data
                        // $('#rincianTabel tbody').empty();

                        $.ajax({
                            url: url,
                            dataType: 'json',
                            success: function(response) {

                                $('input #name').value(response.name);

                                // Display Modal
                                $('#rincianModal').modal('show');
                            }
                        });
                    }
                });

            });
        </script>
    @endpush

    @push('vendorcss')
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    @endpush

    @push('vendorjs')
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    @endpush

    @push('pagejs')
        {{-- <script src="{{ asset('assets/js/app-user-list.js') }}"></script> --}}
    @endpush
@endsection

resources/views/set_pengguna/modal_tambah_pengguna.blade.php
<div class="modal fade" id="tambah-pengguna" data-bs-backdrop="static" tabindex="-1">
    <div class="modal-dialog">
        <form class="modal-content" action="{{ route('setpengguna.store') }}" method="post">
            @csrf
            <div class="modal-header">
                <h5 class="modal-title" id="backDropModalTitle">Tambah Data Pengguna</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row g-2">
                    <div class="col mb-3">
                        <label for="username" class="form-label">Username <i class='bx bx-error-circle'></i></label>
                        <input type="text" name="username" id="username" class="form-control" placeholder="Enter Username" required />
                    </div>
                    <div class="col mb-3">
                        <label for="password" class="form-label">Password <i class='bx bx-error-circle'></i></label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Enter Password" required />
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col mb-3">
                        <label for="organization" class="form-label">Kode SIMA KLPBU <i class='bx bx-error-circle'></i></label>
                        <input type="text" name="kode_klpbu_id" id="organization" class="form-control" placeholder="Enter Kode Sima KLPBU" required />
                    </div>
                    <div class="col mb-3">
                        <label for="klaster" class="form-label">Klaster BU <i class='bx bx-error-circle'></i></label>
                        <select class="form-select" id="klaster" name="klaster_id" required>
                            <option selected>Pilih klaster</option>
                            @foreach ($klaster as $klaster)
                                <option value="{{ $klaster->id }}">{{ $klaster->nama_klaster }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" name="name" id="name" class="form-control" placeholder="Enter Name" />
                    </div>
                    <div class="col mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="text" name="email" id="email" class="form-control" placeholder="Enter Email" />
                    </div>
                </div>
                <div class="row g-2">
                    <div class="col mb-3">
                        <label for="phone" class="form-label">Phone</label>
                        <input type="number" name="phone" id="phone" class="form-control" placeholder="Enter Phone Number" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">
                    Close
                </button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
</div>