routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\QaController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\ParamController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\PenggunaController;
use App\Http\Controllers\ProfilbuController;
use App\Http\Controllers\SetParamController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MyProfileController;
use App\Http\Controllers\SetKlasterController;
use App\Http\Controllers\SetPenggunaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [LoginController::class, 'index'])->middleware('guest')->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.post');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout.post');

//all
Route::get('/', [DashboardController::class, 'index'])->middleware('auth')->name('dashboard');
Route::resource('/myprofile', MyProfileController::class)->middleware('auth');

//admin
Route::resource('/qa', QaController::class)->middleware('admin');
Route::resource('/setpengguna', SetPenggunaController::class)->middleware('admin');
Route::resource('/setparam', SetParamController::class)->middleware('admin');
Route::get('/setting/sima_klpbu', [SettingController::class, 'sima_klpbu'])->middleware('admin')->name('set_simaklpbu');

//mitra
Route::resource('/profilebu', ProfilbuController::class)->middleware('mitra');
Route::resource('/parameter', ParamController::class)->middleware('mitra');

app/Http/Controllers/SetParamController.php
<?php

namespace App\Http\Controllers;

use App\Models\Param;
use App\Models\Dimensi;

use Illuminate\Http\Request;
use App\Models\Deskripsiskor;

class SetParamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $param = Param::all();

        $data = [
            'param' => $param,
        ];
        return view('set_param.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $param = Param::where('id', $id)->first();
        $dimensi = Dimensi::all();
        $deskripsiskor = Deskripsiskor::where('param_id', $id)->first();
        $data = [
            'param' => $param,
            'deskripsiskor' => $deskripsiskor,
            'dimensi' => $dimensi
        ];
        return view('set_param.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($id);
        $dataParam = [
            'dimensi_id' => $request->dimensi,
            'tujuan' => $request->tujuan,
            'deskripsi' => $request->deskripsi,
            'ref' => $request->ref,
            'pertanyaan' => $request->pertanyaan
        ];
        Param::where('id', $id)->update($dataParam);
        $dataDeskripsiskor = [
            'skor0' => $request->skor0,
            'skor1' => $request->skor1,
            'skor2' => $request->skor2,
            'skor3' => $request->skor3,
            'skor4' => $request->skor4,
            'skor5' => $request->skor5,
        ];
        Deskripsiskor::where('param_id', $id)->update($dataDeskripsiskor);

        return redirect()->back()->with('success', 'Update data berhasil!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/set_param/edit.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <ul class="nav nav-pills flex-column flex-md-row mb-3">
            <li class="nav-item me-3">
                <a class="nav-link active" href="{{ route('setparam.index') }}"><i class='bx bx-left-arrow-alt'></i> Data Parameter</a>
            </li>
        </ul>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    @if (session()->has('success'))
                        <div class="alert alert-primary my-3 mx-3 alert-dismissible" role="alert">
                            {{ session('success') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    @if (session()->has('deleted'))
                        <div class="alert alert-danger my-3 mx-3 alert-dismissible" role="alert">
                            {{ session('deleted') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    <div class="card-body">
                        <form class="card-body" method="post" action="{{ route('setparam.update', $param->id) }}">
                            @csrf
                            @method('put')
                            <h5 class="">Rincian Parameter : {{ $param->id }}</h5>

                            <div class="row g-3 mt-3">
                                <label class="col-sm-2 col-form-label" for="dimensi">Dimensi</label>
                                <div class="col-sm-10">
                                    <select id="dimensi" class="form-select" name="dimensi">
                                        <option>Pilih Dimensi</option>
                                        @foreach ($dimensi as $dimensi)
                                            <option value="{{ $dimensi->id }}" @if ($param->dimensi_id == $dimensi->id) selected @endif>{{ $dimensi->deskripsi }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <label class="col-sm-2 col-form-label" for="tujuan">Tujuan</label>
                                <div class="col-sm-10">
                                    <textarea id="tujuan" class="form-control" name="tujuan" rows="3">{{ $param->tujuan }}</textarea>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <label class="col-sm-2 col-form-label" for="deskripsi">Deskripsi</label>
                                <div class="col-sm-10">
                                    <textarea id="deskripsi" class="form-control" name="deskripsi" rows="3">{{ $param->deskripsi }}</textarea>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <label class="col-sm-2 col-form-label" for="referensi">Referensi</label>
                                <div class="col-sm-10">
                                    <textarea id="referensi" class="form-control" name="ref" rows="3">{{ $param->ref }}</textarea>
                                </div>
                            </div>
                            <div class="row mt-2">
                                <label class="col-sm-2 col-form-label" for="pertanyaan">Pertanyaan</label>
                                <div class="col-sm-10">
                                    <textarea id="pertanyaan" class="form-control" name="pertanyaan" rows="3">{{ $param->pertanyaan }}</textarea>
                                </div>
                            </div>
                            <hr class="my-4 mx-n4" />
                            <h5>Deskripsi Skor Parameter : {{ $param->id }}</h5>
                            <div class="row g-3 mt-3">
                                <div class="row mt-2">
                                    <label class="col-sm-2 col-form-label" for="skor0">Skor 0</label>
                                    <div class="col-sm-10">
                                        <textarea id="skor0" class="form-control" name="skor0" rows="3">{{ $param->deskripsiskor->first()->skor0 }}</textarea>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <label class="col-sm-2 col-form-label" for="skor1">Skor 1</label>
                                    <div class="col-sm-10">
                                        <textarea id="skor1" class="form-control" name="skor1" rows="3">{{ $param->deskripsiskor->first()->skor1 }}</textarea>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <label class="col-sm-2 col-form-label" for="skor2">Skor 2</label>
                                    <div class="col-sm-10">
                                        <textarea id="skor2" class="form-control" name="skor2" rows="3">{{ $param->deskripsiskor->first()->skor2 }}</textarea>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <label class="col-sm-2 col-form-label" for="skor3">Skor 3</label>
                                    <div class="col-sm-10">
                                        <textarea id="skor3" class="form-control" name="skor3" rows="3">{{ $param->deskripsiskor->first()->skor3 }}</textarea>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <label class="col-sm-2 col-form-label" for="skor4">Skor 4</label>
                                    <div class="col-sm-10">
                                        <textarea id="skor4" class="form-control" name="skor4" rows="3">{{ $param->deskripsiskor->first()->skor4 }}</textarea>
                                    </div>
                                </div>
                                <div class="row mt-2">
                                    <label class="col-sm-2 col-form-label" for="skor5">Skor 5</label>
                                    <div class="col-sm-10">
                                        <textarea id="skor5" class="form-control" name="skor5" rows="3">{{ $param->deskripsiskor->first()->skor5 }}</textarea>
                                    </div>
                                </div>
                            </div>
                            <div class="pt-4 text-center">
                                <button type="submit" class="btn btn-primary me-sm-3 me-1">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- / Content -->

    @push('vendorcss')
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    @endpush

    @push('vendorjs')
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    @endpush

    @push('pagejs')
        {{-- <script src="{{ asset('assets/js/app-user-list.js') }}"></script> --}}
    @endpush
    <!-- Ineline JS-->.
    @push('inlinejs')
        <script>
            $(document).ready(function() {
                $('#set_param').DataTable();
            })
        </script>
    @endpush
@endsection

resources/views/set_param/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="container-xxl flex-grow-1 container-p-y">
        <ul class="nav nav-pills flex-column flex-md-row mb-3">
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('setparam.index') }}"><i class="bx bx-list-ul me-1"></i> Data Parameter</a>
            </li>
        </ul>

        <!-- Statistic users -->
        {{-- @include('set_pengguna.statistic') --}}
        <!-- Users List Table -->
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    @if (session()->has('success'))
                        <div class="alert alert-primary my-3 mx-3 alert-dismissible" role="alert">
                            {{ session('success') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    @if (session()->has('deleted'))
                        <div class="alert alert-danger my-3 mx-3 alert-dismissible" role="alert">
                            {{ session('deleted') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    <div class="card-body">
                        <div class="table-responsive table-nowrap">
                            <table class="table table-hover" id="set_param">
                                <thead>
                                    <tr>
                                        <th>PK</th>
                                        <th>FK</th>
                                        <th>Tujuan</th>
                                        <th>Deskripsi</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody class="table-border-bottom-0">
                                    <div class="row">
                                        @foreach ($param as $param)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $param->dimensi_id }}</td>
                                                <td>{{ $param->tujuan }}</td>
                                                <td>{{ $param->deskripsi }}</td>
                                                <td>
                                                    <a class="btn text-white btn-sm btn-warning editparam" href="{{ route('setparam.edit', $param->id) }}">
                                                        <i class="bx bxs-pencil"></i> </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </div>

                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer border-top">
                            {{--  --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- / Content -->

    @push('vendorcss')
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
    @endpush

    @push('vendorjs')
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
    @endpush

    @push('pagejs')
        {{-- <script src="{{ asset('assets/js/app-user-list.js') }}"></script> --}}
    @endpush
    <!-- Ineline JS-->.
    @push('inlinejs')
        <script>
            $(document).ready(function() {
                $('#set_param').DataTable();
            })
        </script>
    @endpush
@endsection